docker_apt_release_channel: 'stable'
ubuntu_last_lts:  'focal'
docker_apt_repository: 'deb https://download.docker.com/linux/ubuntu {{ ubuntu_last_lts }} {{ docker_apt_release_channel }}'
docker_group_members: 
  - "{{ lookup('env','CURRENT_USER') }}"
